name: simapres
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  http: ^1.1.0
  csv: ^5.0.2
  flutter:
    sdk: flutter
  dio: ^5.3.2
  image_picker:
  intl: ^0.17.0
  pretty_animated_buttons: ^0.0.1
  dropdown_button2: ^2.3.8
  google_fonts: ^6.1.0
  button_animations: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/SIMAPRESputih.png
    - assets/SIMAPRES.png
    - assets/bg.png

