name: simapres
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  http: ^1.1.0
  csv: ^5.0.2
  flutter:
    sdk: flutter
  dio: ^5.3.2
  image_picker:
  intl: ^0.17.0
  pretty_animated_buttons: ^0.0.1
  dropdown_button2: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: Inter 
      fonts:
        - asset: fonts/Inter-Black.ttf
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-ExtraBold.ttf
        - asset: fonts/Inter-ExtraLight.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf
